
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<link rel="stylesheet" href="css/BackToTop.jquery.css" type="text/css" />
</head>

<body>

<ul>
	<li>Full documentation on <a href="http://www.myjqueryplugins.com/BackToTop">MyjQueryPlugins.com/BackToTop</a></li>
	<li>Live demonstration on <a href="http://www.myjqueryplugins.com/BackToTop/demo">BackToTop demonstration page</a></li>
</ul>
<h1>BackToTop plugin</h1>
<h2>A very very very long paragraph</h2>
<p>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum pretium sagittis dui, non consectetur tortor tempus vitae. Phasellus quam dui, tincidunt sit amet consequat sit amet, porta ut felis. Proin sapien felis, porta sed ornare a, lacinia sed est. Nulla facilisi. Donec quis ligula nec nunc eleifend luctus interdum at nisl. Aliquam semper pellentesque fermentum. Aenean non erat ligula. Maecenas egestas enim eu ante varius venenatis. Sed imperdiet iaculis turpis, sed gravida enim ultricies id. Vivamus placerat dolor sit amet nulla fringilla fringilla.
Duis sem libero, elementum vitae vestibulum ac, congue sed velit. Etiam semper ultricies dui a dictum. Nunc commodo, purus non tempus placerat, urna ipsum fermentum libero, a pretium est arcu quis mi. Ut a justo id magna tempus volutpat. Duis ac dignissim mi. Integer mauris nibh, varius sit amet blandit ut, auctor nec nisi. Nullam tincidunt dictum tortor in sodales. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi pellentesque, felis auctor tincidunt tristique, tellus massa porta arcu, eget malesuada velit risus vitae quam. In vitae orci urna, quis tincidunt magna. Sed feugiat tempor magna, ut lobortis sapien aliquam in. Curabitur tempor pulvinar tempor. Nulla facilisi.
Duis vestibulum fermentum lacinia. Praesent hendrerit arcu sed purus suscipit lacinia. Praesent nec lacinia quam. Sed id justo et velit eleifend ultrices sit amet id nibh. Suspendisse potenti. Suspendisse sed volutpat turpis. Pellentesque dictum tellus quis tortor porta imperdiet. Ut mollis, odio vitae posuere aliquet, libero justo volutpat justo, ac aliquet orci turpis id arcu. Donec a fringilla massa. Nulla facilisi. Nam sem metus, varius non viverra in, tristique eu mi. Pellentesque volutpat, orci nec eleifend mattis, tortor quam faucibus velit, ut sollicitudin velit elit sed quam.
Praesent interdum, turpis non congue consequat, mauris ipsum pharetra est, adipiscing congue erat ante eget ante. Nullam iaculis fringilla sodales. Etiam pellentesque congue tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras mollis nunc a dui luctus sagittis. Vestibulum hendrerit consequat turpis, ac lobortis purus molestie sed. Vivamus pretium metus ac est scelerisque venenatis. Suspendisse sodales dolor sed massa malesuada eu consequat odio eleifend. Aliquam accumsan auctor lacinia. In semper est ut nisl volutpat at egestas ligula vulputate. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris bibendum bibendum eleifend. Donec id neque magna.
Vivamus orci metus, ornare eu placerat id, porttitor ut ante. Nunc vel suscipit mi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam laoreet consequat metus, non sodales lacus tincidunt nec. Vivamus augue tellus, fermentum vitae luctus laoreet, porttitor vel quam. Maecenas gravida ullamcorper ultricies. Sed risus tortor, gravida nec vehicula ac, dignissim sed massa. Mauris non velit euismod quam tristique hendrerit.
Curabitur vitae lorem urna, viverra imperdiet diam. Nam varius pretium pellentesque. Donec nunc ipsum, laoreet id pulvinar et, sodales id dolor. Donec gravida semper placerat. Aenean eros lacus, convallis eu iaculis vel, accumsan non nisl. Morbi venenatis condimentum eros eu vulputate. Nulla pulvinar ultricies gravida. Ut id dolor non nunc dapibus vulputate. Cras a ipsum tellus, in gravida ipsum. Nullam ante mauris, gravida ac ornare in, vehicula quis dolor. Duis vel nisi ut purus tempus congue at sit amet nisl. Vivamus blandit dignissim facilisis. Sed dignissim varius lacinia.
Nunc gravida massa molestie orci congue molestie. Praesent porta, augue at laoreet condimentum, tellus est tempus nunc, varius cursus dolor massa eu nulla. Aliquam eu turpis eu magna lobortis euismod. Etiam non aliquam urna. Integer accumsan pharetra placerat. Cras at semper felis. Nulla rhoncus placerat varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin sed est est, commodo ornare elit. Fusce fermentum, nunc eu malesuada tristique, diam lectus fermentum nisl, at sagittis urna diam non elit. Phasellus accumsan, mauris eu tincidunt sagittis, purus quam pulvinar eros, id tempus ligula nibh sodales arcu. Duis non justo purus, vel facilisis elit. Nam blandit risus sed mauris convallis eget lobortis sapien vulputate. Suspendisse potenti.
Nulla bibendum libero sed tortor porta quis semper metus facilisis. Praesent tristique egestas ipsum, eget molestie tortor accumsan eget. Nulla at risus lacus. Aenean ac augue sed lorem gravida suscipit. Proin vel lectus ultrices nibh egestas pretium et vel nisi. Integer erat augue, sodales vitae fringilla at, vehicula fringilla lorem. Quisque ac odio sed leo pellentesque malesuada. Nunc tempus massa sit amet nisi sollicitudin consectetur. Vestibulum laoreet lorem ut nibh scelerisque sodales. Nulla nec erat risus.
Aenean sit amet eros lorem, in dignissim sapien. Aliquam cursus imperdiet ligula, ultricies sollicitudin dolor aliquam nec. Vestibulum placerat imperdiet fringilla. Curabitur vel erat mi. Integer elementum faucibus libero, sit amet sagittis lorem luctus a. Praesent id orci id diam aliquam laoreet. Aliquam mattis velit sed turpis tempor suscipit. Nunc mattis iaculis tellus aliquam convallis. In quis sollicitudin libero. Morbi dignissim dui vel massa rutrum mollis. Sed eros ante, convallis eget placerat a, pulvinar non metus. Nam ante odio, vestibulum sed hendrerit et, elementum non quam. Curabitur blandit turpis id sem auctor vulputate.
Etiam porttitor tortor volutpat quam porta sit amet laoreet sapien faucibus. Etiam ligula ligula, vestibulum id congue sodales, tincidunt in nibh. Quisque iaculis dui non ante convallis malesuada. Suspendisse urna libero, auctor quis dapibus quis, luctus non neque. Nulla eu mi ut mauris cursus vulputate. Duis bibendum, nibh id luctus euismod, nunc nisi faucibus purus, id pulvinar sem erat id est. Nulla ac turpis orci, nec auctor leo. Ut imperdiet volutpat lacus et sollicitudin. Sed auctor congue odio a congue. Vestibulum vehicula aliquam viverra. Nam sed aliquam dui. Ut commodo sapien eget nulla lacinia pellentesque. Vivamus vehicula auctor urna nec suscipit.
Curabitur dignissim nunc id est aliquam vel volutpat nisl fringilla. Morbi vitae dui augue. In quis ante magna, vel mattis turpis. Morbi magna eros, gravida quis venenatis at, faucibus a justo. Mauris augue quam, lacinia sed ultrices quis, gravida sed lectus. Mauris vel nunc varius arcu imperdiet convallis nec et elit. Nulla suscipit, lacus ut placerat pellentesque, dolor mauris posuere odio, sed suscipit nunc urna ut nisl. Duis et nisl ante. Vivamus non elit nulla, vitae imperdiet ipsum. In placerat, lorem a dignissim consectetur, velit magna venenatis mauris, sit amet vestibulum risus dui at urna. Cras sodales, libero non molestie molestie, urna ante luctus nunc, eget dictum erat risus sit amet ipsum. Quisque pretium aliquet nisi in faucibus.
Proin pulvinar magna eu magna hendrerit pulvinar. Nam lorem lectus, varius id luctus ac, pulvinar sed metus. Nunc varius urna et ligula lobortis feugiat. Curabitur ut auctor quam. Aliquam vitae lectus eu ante ullamcorper mollis. Vestibulum id justo leo. Vivamus facilisis adipiscing magna, nec bibendum augue adipiscing quis. Etiam a posuere justo. Proin at consequat enim. Sed malesuada odio at augue accumsan mollis. Quisque consectetur cursus ipsum, sit amet aliquet ante consequat vel. Vestibulum neque augue, pulvinar ultrices pretium quis, facilisis quis nibh. Nulla hendrerit nulla at eros laoreet cursus.
Donec blandit leo vel risus egestas auctor. Donec vel eros ac elit blandit blandit. Etiam consequat semper lacinia. Donec mattis consequat nunc nec ullamcorper. Cras metus metus, gravida sit amet elementum et, molestie at eros. Curabitur bibendum interdum nisl. Maecenas quam elit, ultrices non venenatis vitae, varius vitae odio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque nec erat massa. Donec iaculis, nulla ac dictum hendrerit, massa turpis elementum nisl, ac dapibus elit justo at magna. Donec consectetur, nisi malesuada porttitor ullamcorper, tortor mauris eleifend massa, nec lacinia urna sem vitae nisi. Donec viverra tincidunt dui vitae pretium. Sed at dignissim neque. Nunc est leo, porta vel ultrices in, consectetur at sem.
Etiam sit amet odio nec massa pulvinar fringilla. Etiam hendrerit auctor tellus ac tempus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Mauris gravida purus a ante iaculis et consectetur turpis porta. Curabitur condimentum vehicula est, sed gravida mi dapibus vitae. Fusce non arcu mi. Aliquam erat volutpat. Proin justo massa, convallis euismod pharetra ac, dignissim quis urna. Aenean ipsum dolor, ultrices vitae auctor commodo, elementum vitae lectus. Maecenas condimentum hendrerit felis vel commodo. Sed id erat in magna pellentesque egestas. Etiam vel quam mollis erat tincidunt ullamcorper id ac est. Vestibulum ultricies nisi eget lectus tempus ac viverra ipsum feugiat. Mauris vitae ipsum eget dolor imperdiet pulvinar. Fusce a molestie quam.
Nam at scelerisque ipsum. Duis ac neque erat, nec tempus neque. Duis viverra augue id nibh consequat sagittis. Donec bibendum dictum augue ut ultricies. Duis sagittis mollis leo vel consectetur. Nam adipiscing elit vitae nisi commodo gravida. Morbi eleifend pellentesque nibh sit amet convallis. Nam ac sem neque, eu porttitor nulla. Donec laoreet iaculis neque, in imperdiet tellus lobortis id. Mauris sodales dolor tortor. Praesent interdum consequat dui nec tristique.
Nam vestibulum aliquet tortor, id luctus dui bibendum id. Phasellus eu urna nec arcu molestie tincidunt. In in nisl purus. Nullam eleifend, lectus non feugiat semper, leo lacus sagittis nisl, a rutrum elit sem in elit. Pellentesque vitae purus leo, a ornare mauris. Praesent vulputate pellentesque purus. Duis mattis, sem nec euismod accumsan, nibh justo ornare nisi, eu convallis odio turpis nec neque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus a auctor sem. Morbi egestas mattis dui ut egestas.
Duis ac purus eros. Fusce dolor nibh, auctor nec condimentum et, convallis eget dolor. Maecenas consequat posuere sapien, eget vestibulum nunc posuere quis. Sed eu malesuada urna. Cras ante elit, rutrum vitae egestas sed, gravida quis nunc. Nunc suscipit sapien vel quam suscipit et tristique magna facilisis. Aenean lacus erat, tempor in dignissim in, imperdiet non leo. Curabitur sed dolor id sem tincidunt iaculis ac eu eros. Maecenas egestas vulputate lectus, tristique dignissim quam molestie non. Nulla a orci id tellus feugiat vulputate id nec lacus. Pellentesque ac leo dolor, sed hendrerit dui. Nullam commodo metus id nibh imperdiet nec ullamcorper nunc lacinia. Cras eget sapien sed enim dapibus molestie. Duis sed sapien sit amet eros commodo cursus. Donec sagittis porttitor sagittis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
In congue euismod erat, et convallis tortor commodo in. Maecenas eget orci iaculis nisl vehicula mollis. Sed eu mi eu neque volutpat tempus. Pellentesque sodales feugiat massa non dignissim. Sed justo nibh, tempus ultrices fermentum cursus, dictum sed nisl. Etiam eget arcu lectus. Vivamus dictum libero vel lectus scelerisque varius. Duis ut ligula quam, sed mollis dui. Nunc vitae massa ligula, et tristique sem. Pellentesque cursus ultricies mauris, nec vehicula dolor imperdiet vitae.
Proin hendrerit egestas faucibus. Aliquam molestie mollis eros id semper. Nullam sollicitudin, nulla nec tristique vestibulum, quam arcu venenatis odio, sit amet sollicitudin odio sapien vel enim. Sed convallis, eros a consectetur volutpat, justo sapien eleifend metus, et consequat quam velit at enim. Nullam lectus quam, auctor quis laoreet ac, ornare ac dui. In adipiscing aliquet arcu, eget feugiat urna blandit quis. Nunc eleifend faucibus tincidunt. Maecenas nibh lacus, suscipit nec ornare eget, consectetur id nisl. Nunc facilisis elit ut neque commodo cursus. Aliquam erat volutpat. In fermentum ultricies elit id ornare. Nam interdum pellentesque felis, vel tempor lorem aliquam vitae. Pellentesque suscipit mi sit amet nunc viverra eu mollis nulla scelerisque. Vestibulum nibh ligula, iaculis ut mattis non, lacinia ut neque. Proin sit amet fringilla sapien. Integer elementum neque ut augue rhoncus placerat.
Curabitur sed ornare magna. Donec ante lorem, tempor vel dapibus eu, scelerisque sit amet mi. Proin volutpat pellentesque est imperdiet scelerisque. Morbi leo nulla, egestas sit amet pulvinar auctor, elementum a eros. In eleifend rutrum tincidunt. Donec augue felis, luctus ut consequat rhoncus, lobortis in turpis. Mauris eget ipsum sit amet purus dignissim viverra. Integer mollis, ipsum at gravida rhoncus, est augue fermentum sapien, sed facilisis elit nunc a turpis. Etiam commodo vulputate imperdiet. Sed rutrum faucibus eros quis pretium. Quisque fringilla venenatis facilisis. Integer congue, ligula vel cursus laoreet, urna elit placerat tortor, vel suscipit tortor justo quis ligula. Sed sollicitudin felis vitae lorem consectetur rhoncus. Pellentesque ultricies molestie erat pellentesque porttitor. Suspendisse feugiat neque et mauris pharetra in varius turpis pellentesque.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nibh diam, tempus in condimentum eu, sagittis non nibh. In et eros gravida velit congue vulputate sit amet ac mi. Nulla id velit massa. Nunc et sem at diam faucibus scelerisque. Ut sapien purus, pulvinar nec euismod sit amet, laoreet a ipsum. Quisque in facilisis ligula. Sed pellentesque lorem quis ligula ullamcorper eget bibendum metus convallis. Suspendisse hendrerit elit nec velit aliquam at bibendum arcu blandit. Fusce pulvinar, mauris ac fermentum ultrices, orci sapien sagittis enim, eget mattis ligula metus nec magna. Cras eu elementum orci. Donec dictum velit et felis fermentum vel tristique leo commodo. Etiam quis urna sed lacus ullamcorper facilisis convallis sit amet diam. Integer convallis, sem id sagittis posuere, lorem massa placerat dui, eget suscipit ligula augue vel orci. Fusce feugiat tellus at elit ultricies vel tincidunt nisi porttitor.
Vestibulum gravida, tellus et dignissim sodales, metus purus dignissim quam, eu consequat sem lorem vitae magna. Etiam laoreet condimentum ipsum in tempor. Vivamus mollis, justo non malesuada placerat, felis ipsum tristique neque, eu dignissim lacus nibh id dolor. Aliquam varius, felis sit amet bibendum interdum, dui libero ultrices risus, nec blandit turpis eros at magna. Integer a arcu tellus. Aenean porta, nulla a tempor accumsan, nunc sapien pharetra orci, sit amet hendrerit nisi tortor sed enim. Donec mauris sem, rutrum et fermentum eget, eleifend nec massa.
Donec congue imperdiet nunc a bibendum. Nulla magna sapien, euismod eu tincidunt sed, gravida sed lorem. Donec justo magna, convallis nec varius eu, auctor ac nulla. Etiam eleifend suscipit malesuada. In hac habitasse platea dictumst. Nunc ornare, tellus quis dictum aliquam, ipsum quam fringilla eros, et sagittis justo tellus quis enim. Nullam vitae enim suscipit massa tristique adipiscing. Suspendisse id scelerisque mi. Aliquam non massa purus, in rhoncus augue. Nulla facilisi. Aliquam vel mauris eu diam aliquam placerat non at tellus. Suspendisse quis cursus dolor. Mauris sed tortor est, eget tristique tortor.
Nulla nec magna et elit tincidunt fringilla sed a leo. Praesent nec dictum est. Cras quam eros, mollis quis fringilla et, varius vitae elit. Vivamus non lorem arcu, eget placerat mauris. Pellentesque eget sem a velit luctus pharetra. Curabitur tristique gravida ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
Nulla non velit nulla. Proin vitae ante in justo bibendum tempus. Etiam auctor, felis id facilisis bibendum, tellus augue tincidunt elit, ac mollis eros odio nec massa. Aliquam elit augue, volutpat at laoreet tempus, porta ut eros. Ut nisl sem, imperdiet et placerat at, egestas eget lectus. Integer at mauris sed nulla vehicula condimentum. Maecenas eget risus leo, eget egestas erat. Vivamus vel bibendum eros. Aliquam erat volutpat. Vestibulum sem elit, commodo ac consectetur non, aliquet non sapien.
Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam venenatis bibendum magna, vitae euismod nunc egestas sed. Donec volutpat aliquet pellentesque. Fusce eu sapien eget elit bibendum placerat in porttitor eros. Curabitur elementum, dui sit amet pellentesque rhoncus, sem tellus fringilla massa, sit amet condimentum ante velit vel erat. Ut gravida, augue semper rutrum blandit, mi neque pharetra libero, sit amet convallis turpis sem eget libero. Aenean vel ullamcorper sem. Aenean et erat vitae mauris convallis scelerisque non quis magna. Nam eu lacus at mi scelerisque commodo mollis et justo. Proin sodales tempus dui varius gravida. Donec tempus sollicitudin orci, sed varius arcu accumsan eget. Morbi et nunc diam, sit amet gravida dui. Curabitur vitae consectetur felis. Proin pretium accumsan molestie.
Nulla eu lectus diam. Duis hendrerit, turpis et porttitor condimentum, nulla justo accumsan ligula, sit amet pharetra orci diam in tellus. Ut in lacus et nulla commodo euismod. Aliquam erat volutpat. Sed ligula mauris, fringilla vel imperdiet id, interdum et nisl. Donec elit mauris, faucibus id sagittis sagittis, lacinia ac risus. In faucibus metus id ante mollis dignissim. Aenean justo tortor, rhoncus vitae mollis nec, commodo sed nunc. Integer vel diam diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer placerat blandit lorem at elementum.
Maecenas bibendum lacinia nisi nec aliquet. Sed eleifend nunc sit amet purus lacinia rhoncus. Sed tempus consequat egestas. Donec magna nunc, aliquet nec fermentum a, pulvinar vel augue. Mauris interdum, enim id ultrices convallis, nibh purus semper purus, sed accumsan dui eros eu dolor. Curabitur porttitor purus ipsum. Duis aliquet, tellus ut dapibus eleifend, nisl lacus semper ante, at malesuada arcu sapien sed diam. Phasellus cursus congue faucibus. Curabitur felis est, pellentesque id congue a, sodales at augue.
Nam feugiat dui molestie dui aliquet posuere. Curabitur tellus sem, dictum a interdum ut, tincidunt nec nulla. Sed eu neque non sem feugiat ultricies non et metus. Nulla ac lacus tortor, eget faucibus purus. Sed at purus elit, id blandit mi. Etiam vestibulum euismod euismod. Phasellus semper, diam id aliquet adipiscing, ante nisi pretium erat, non egestas sem odio eu ante. Vivamus ante quam, fringilla non mollis quis, tristique a mi. Duis suscipit tellus sed neque pharetra fermentum. Morbi eleifend, dolor condimentum posuere accumsan, urna odio luctus mauris, sed eleifend sem metus id tortor. Suspendisse aliquam porta tristique. Morbi non tortor et magna condimentum mollis. In at lacus at erat luctus faucibus. Praesent nec augue eu nunc dignissim venenatis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Fusce a dolor id quam egestas interdum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris nec accumsan enim. Fusce justo nisi, commodo vel mollis vitae, dignissim et erat. Donec commodo vestibulum commodo. Quisque eu turpis vel justo scelerisque pellentesque at ac mi. Nulla dictum turpis vitae leo porta vulputate. Duis aliquam orci ut purus dignissim sollicitudin. Integer congue porta massa, sed rutrum nisi laoreet nec. Vestibulum condimentum congue justo, ut congue purus aliquet ac. Etiam mattis dignissim libero at imperdiet.
Phasellus ultrices enim sit amet nibh sodales fermentum. Donec tempor metus vitae enim imperdiet rutrum. Nunc sapien purus, venenatis in interdum at, vestibulum quis orci. Nunc dapibus bibendum malesuada. Donec vel tempor sapien. Donec vehicula lobortis vehicula. Ut sed odio urna, sit amet hendrerit nulla. Nam sit amet purus eu libero laoreet malesuada pharetra vel enim. Proin a quam enim, et posuere erat. Nunc justo risus, congue in cursus sit amet, porttitor condimentum erat.
Sed sagittis nunc at nibh accumsan dictum. Nullam non nisi vitae urna dapibus tempus id quis nibh. Suspendisse potenti. Curabitur dui leo, ornare id mollis in, mollis vel turpis. Vestibulum a arcu vitae diam cursus tincidunt ac fermentum erat. Nulla lectus justo, mattis sit amet cursus eu, laoreet et dui. Sed vulputate ligula at velit semper imperdiet. Vivamus laoreet aliquam eros ut tempus. Nulla facilisi. Maecenas et vestibulum turpis. Nam non condimentum urna.
Curabitur scelerisque dui eu velit scelerisque pulvinar. Phasellus viverra ante nec nisi aliquet vitae laoreet metus rutrum. Nulla facilisi. Duis congue pulvinar velit ut blandit. Aenean faucibus pulvinar mauris, a accumsan leo porta ut. Aliquam erat volutpat. Donec commodo quam ut tortor cursus eu dapibus dui auctor. Vestibulum mollis imperdiet tellus a condimentum. Morbi libero dui, iaculis in feugiat vel, pulvinar consequat tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse convallis euismod eros. Vivamus tristique, erat vitae vulputate feugiat, nibh felis pretium justo, quis ultrices ante dolor a massa. Etiam nibh nisl, pharetra ut faucibus in, varius vel odio. Curabitur eget sapien velit, et rhoncus tortor. Donec pellentesque consequat ante vel adipiscing.
Fusce ut neque eget urna accumsan consequat sed ut justo. Integer pharetra felis vitae quam lobortis et gravida orci placerat. Vivamus non dui sapien, sed blandit nisl. Sed pulvinar condimentum aliquam. In magna nisi, pellentesque ut convallis eget, sagittis ac justo. Praesent sit amet justo bibendum mi pellentesque porta nec quis lectus. In suscipit porta diam, eget congue mauris condimentum ut. Aliquam luctus luctus orci. Nunc egestas auctor lacus et ultrices. Proin quis ullamcorper lacus. Nulla dictum mi et turpis pellentesque et scelerisque ipsum faucibus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Sed porttitor rutrum leo, sit amet sollicitudin elit porttitor tristique. Nullam commodo diam at metus dictum bibendum. Sed faucibus, sem vel placerat scelerisque, nulla sem consectetur dolor, vitae elementum tortor dolor ut nisi. Maecenas non mauris sed urna ultrices pulvinar. Integer fermentum consequat erat ut ultricies. Duis sapien sem, dignissim eget vulputate eget, tempus nec purus. Vestibulum turpis nisi, pharetra viverra porttitor vel, pharetra vitae nisi. Suspendisse nec mauris justo, in pulvinar arcu. Mauris mattis ultricies tortor, eu tristique urna aliquam non. Nullam vel orci sem, vitae ultrices est. Vivamus arcu massa, posuere ac rhoncus id, vestibulum at turpis. Pellentesque non tortor mauris, nec luctus augue. Aenean volutpat dui ut libero interdum at dictum lorem venenatis. Nam nec ligula nec turpis pellentesque accumsan at aliquet magna. Vivamus nec odio nisl. In urna leo, fringilla dignissim tristique eu, blandit imperdiet ligula.
Curabitur euismod mattis lectus, id fringilla arcu tempor eu. Nullam elit enim, vulputate non accumsan eu, viverra vitae metus. Aliquam mi lacus, mollis in rhoncus non, sagittis nec odio. Fusce nunc eros, aliquam ac dignissim consectetur, blandit eu nibh. Integer viverra sodales leo, in vehicula eros rutrum sed. Nulla facilisi. Curabitur non augue eu mi scelerisque aliquet at vel dolor. Suspendisse potenti. Integer elementum elementum nulla, vel facilisis justo pellentesque nec. Phasellus imperdiet fermentum malesuada. Donec tempus odio et nibh gravida egestas. In sed metus ligula. Nunc tempor, ipsum vitae blandit tempor, risus sem ultrices leo, nec aliquam nisi mauris quis dolor. Nam suscipit magna sed risus accumsan hendrerit.
Morbi condimentum sapien quis felis fringilla condimentum. Praesent non felis sit amet dui varius feugiat non ut massa. Vivamus a blandit dui. Mauris vel libero a mauris placerat vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh lectus, tincidunt eget adipiscing a, feugiat sed eros. Donec iaculis lobortis ipsum non interdum. Nunc dictum mollis magna, ac gravida nunc fermentum ac. Phasellus venenatis consectetur enim, a sagittis dolor hendrerit id. Phasellus egestas pretium elementum. Maecenas malesuada fringilla nunc, sed venenatis dolor hendrerit sed.
Fusce ullamcorper suscipit justo, in venenatis libero scelerisque a. Vivamus posuere, sem sed tristique venenatis, libero mi scelerisque lorem, at porta turpis sem eget augue. Sed dui enim, hendrerit eget iaculis nec, rutrum in diam. Morbi ullamcorper placerat dolor at faucibus. Aenean bibendum nunc eu dui feugiat a accumsan nunc ornare. Suspendisse neque lorem, auctor vitae vehicula nec, condimentum in mi. Nulla facilisi. Curabitur orci orci, posuere et adipiscing quis, ullamcorper sagittis felis. Sed porttitor, massa et convallis gravida, purus est volutpat sem, a pretium erat ante vitae velit. In hac habitasse platea dictumst. Phasellus non nulla a orci placerat rutrum a id diam. Integer pulvinar ante et ante auctor et mattis magna rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse sed nisi turpis.
Nunc purus risus, sodales quis facilisis at, rhoncus ut diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum suscipit, eros at egestas mattis, lacus turpis sollicitudin nunc, ac iaculis eros libero id lacus. Vestibulum feugiat sagittis dolor, a laoreet augue lobortis vel. Donec tempus, nisi sit amet consequat sodales, mi ligula tempor diam, a laoreet magna mi aliquam lectus. Cras dapibus hendrerit turpis nec tempus. Vivamus commodo elementum nulla ut dignissim. Quisque non diam ullamcorper leo egestas molestie in eu diam. Aenean dapibus nisi et purus ullamcorper sollicitudin et convallis dui. Cras facilisis tempus est eget lobortis. Sed sit amet ligula ut mauris posuere adipiscing.
Cras et pretium sem. Proin id volutpat orci. Cras dapibus ultrices leo, quis tempus velit feugiat vitae. Nunc posuere cursus velit, sit amet congue erat scelerisque et. Donec in egestas mi. Praesent ac mi nisi. Donec risus quam, gravida ac pellentesque ut, auctor at mauris. In sed justo malesuada justo hendrerit commodo sit amet eget velit. Aenean sed erat non diam pharetra vulputate. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ac justo dui. Nullam egestas magna sed ipsum suscipit ut feugiat leo imperdiet. Aenean adipiscing nunc id odio bibendum feugiat. Sed imperdiet magna sit amet purus pulvinar cursus. Nulla sapien risus, porttitor at placerat a, adipiscing et felis.
Morbi suscipit suscipit pretium. Phasellus iaculis iaculis metus in lacinia. Nam eleifend, tortor quis lobortis volutpat, diam nisi blandit nunc, quis gravida libero nisl vitae neque. Fusce dapibus erat vitae nibh dictum iaculis. Sed id odio eu tellus facilisis tincidunt non eleifend nibh. Praesent vitae massa at massa tempus consequat et in erat. Nullam et justo velit.
Vestibulum vel leo vitae velit tempus luctus. Nullam gravida mollis accumsan. Pellentesque gravida dui vitae orci interdum vel accumsan velit accumsan. In sodales dignissim laoreet. In a lobortis dui. Phasellus sit amet venenatis orci. Nulla tortor ipsum, consequat in sagittis at, tincidunt eu est. In risus lorem, elementum vel bibendum a, bibendum sit amet augue. Fusce lacus eros, tincidunt a ornare sit amet, facilisis nec turpis. Donec gravida malesuada velit vel auctor. Curabitur eget risus et risus congue dignissim. Donec ornare pellentesque nunc, vel gravida urna auctor nec. Nunc posuere laoreet posuere.
Nunc fringilla nunc sed neque ultrices ullamcorper at id tortor. Vivamus rhoncus varius sapien at fringilla. Nam vel ante ipsum, molestie pharetra nunc. Nulla facilisi. Suspendisse mi risus, placerat non interdum tempus, imperdiet et dolor. Aenean vel ligula tellus, eu euismod orci. Fusce eu nisi eros. In eu magna vel erat ultrices tincidunt. In sagittis tristique mauris ornare varius. Aliquam aliquet blandit felis sed sagittis. Phasellus eget diam lorem. Morbi tempor, orci venenatis ultricies tempus, lorem sem ullamcorper arcu, ac ultrices sapien justo eget ligula. Sed posuere scelerisque nibh ut blandit. Suspendisse potenti. Morbi non velit tellus. Nunc ultricies sollicitudin convallis.
Nam in tortor vel tellus elementum scelerisque. In odio leo, varius consequat elementum ac, euismod eget mi. Donec commodo iaculis augue at bibendum. Aenean quis leo in est scelerisque suscipit. Pellentesque vitae ipsum sed turpis auctor eleifend at eu est. Suspendisse lobortis rhoncus felis, sed tempor diam dignissim eget. Nam nulla risus, malesuada quis laoreet ut, posuere vel magna. Sed malesuada mauris ac eros blandit at tempor dui cursus. Nunc sodales enim id turpis ullamcorper ac mollis nibh imperdiet. Ut semper erat arcu.
Morbi posuere, nulla id tempor consequat, risus velit euismod tellus, a ultricies lorem nisi et nisl. Sed sed pretium dolor. Donec pulvinar nisi vel nisi bibendum placerat. In rhoncus, nibh quis gravida consequat, enim nisl eleifend tortor, non fermentum felis leo ut arcu. In et venenatis mi. Fusce congue tincidunt neque a luctus. In et sapien eu sapien scelerisque tristique.
In nec venenatis ligula. Praesent consequat sem sed orci ullamcorper vel convallis erat consequat. Aenean id neque tellus, sit amet lobortis lacus. Vestibulum elementum nisi non mauris facilisis sed congue risus iaculis. Vivamus tempor porttitor nisi at fringilla. Mauris sit amet velit lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas congue lacinia ligula in bibendum. Maecenas quis lectus sit amet libero posuere euismod vestibulum id nibh.
Donec et adipiscing arcu. Curabitur volutpat varius urna ut rutrum. Fusce nisl purus, viverra ut ultricies quis, semper vitae diam. Aliquam egestas, magna non dapibus ornare, nunc justo accumsan lectus, a blandit enim mi non eros. Aenean sollicitudin leo id justo fermentum rhoncus. Proin orci nibh, fringilla quis sollicitudin sit amet, sollicitudin pulvinar urna. Nunc sit amet massa augue, in pellentesque ante. Maecenas ac tellus non nunc convallis placerat ac nec ipsum. Duis scelerisque ipsum ac odio sollicitudin ac gravida sem malesuada. Pellentesque quis massa arcu.
Fusce aliquet elit quis justo tempor porta eget nec diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam pulvinar convallis magna vel bibendum. Duis erat augue, tristique convallis tempus ut, sodales ac tellus. Nulla pellentesque tristique metus non suscipit. Donec rhoncus ante sed massa rutrum vel consequat ante mollis. Vestibulum eget nibh nunc, molestie accumsan massa.
In eu diam id felis facilisis posuere et quis urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum convallis arcu non tortor aliquet at porttitor odio molestie. Phasellus lobortis ligula id libero iaculis eget lobortis diam sagittis. Sed viverra rhoncus feugiat. Proin vel neque a felis semper facilisis eget ac nunc. Aliquam erat volutpat. Donec nec augue mi, accumsan accumsan neque. Praesent eget nulla at nunc malesuada mollis id vitae mauris. Mauris porttitor, nibh ac rutrum sagittis, dui libero accumsan augue, vitae consectetur erat sapien id dui. Ut volutpat lectus sed purus mattis tempor facilisis leo consequat. Morbi a nulla tortor, quis dictum purus. Nam sed justo at nunc euismod rutrum. Aenean pulvinar elit a dui facilisis et luctus erat tincidunt. Proin quis arcu ut felis porttitor vestibulum.
Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla aliquet, velit vel pulvinar dapibus, massa nulla tincidunt sem, non facilisis nibh erat eu purus. Nullam ac accumsan lorem. Praesent euismod placerat erat ac fringilla. Pellentesque dignissim, neque in ullamcorper scelerisque, est neque hendrerit sem, et pretium velit justo sit amet eros. Etiam commodo ante eu tortor ultrices quis ornare odio commodo. Praesent gravida, libero nec rhoncus gravida, eros metus pulvinar turpis, ut placerat sem magna in mauris. Morbi malesuada, velit a convallis placerat, diam mi adipiscing lorem, eu aliquet tellus augue porttitor nisi. Duis vel tortor sem, sed vehicula odio. In rutrum, leo non blandit malesuada, dui mi venenatis lorem, ut adipiscing leo urna nec massa. Ut molestie tristique libero vitae laoreet.
</p>


	<script type="text/javascript" src="jquery/jquery.js"></script>
	<script type="text/javascript" src="jquery/jquery-ui.js"></script>
	<script type="text/javascript" src="jquery/BackToTop.jquery.js"></script>
	<script type="text/javascript">
	$(document).ready(function(){
		BackToTop({
				text : '^ Back to top',
				autoShow : true,
				timeEffect : 800,
				appearMethod : 'slide',
				effectScroll : 'easeOutCubic' /** all effects http://jqueryui.com/docs/effect/#easing */
		});
	});
	</script>
</body>
</html>
